name: TRGoals, MonoTV ve M3U GÃ¼ncelleme Workflow (BirleÅŸik)
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'  
jobs:
  BirlesikGuncelleme:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v4.2.2
        
      - name: Python 3.11.8 YÃ¼kle
        uses: actions/setup-python@v5.3.0
        with:
          python-version: 3.11.8
          
      - name: Gereksinimleri Kur
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools wheel Kekik httpx parsel requests
          
      - name: TRGoals.py Ã‡alÄ±ÅŸtÄ±r
        run: python TRGoals.py
        
      - name: MonoTV.py Ã‡alÄ±ÅŸtÄ±r
        run: python MonoTV.py
        
      

      - name: Alive 1
        run: curl https://kerimmkirac-dproxy.hf.space

      - name: Alive 2
        run: curl https://kerimmkirac-daddylive.hf.space

      - name: Alive 3
        run: curl https://kerimmkirac-daddyliveevents.hf.space

      

      - name: daddylive.m3u dosyasÄ±nÄ± oluÅŸtur 
        run: |
          curl -s "https://raw.githubusercontent.com/GitLatte/temporarylists/refs/heads/main/dl/dl-daddyliveall.m3u" | \
          sed -e 's|https://tinyurl.com/lattedl|https://kerimmkirac-daddylive.hf.space/watch|g' \
              -e 's|https://raw.githubusercontent.com/patr0nq/link/refs/heads/main/tv-logo/vavoo.png|https://raw.githubusercontent.com/kerimmkirac/CanliTvListe/refs/heads/main/subaicon.jpeg|g' \
          > daddylive.m3u

      - name: daddyliveevents.m3u dosyasÄ±nÄ± oluÅŸtur 
        run: |
          curl -s "https://raw.githubusercontent.com/GitLatte/temporarylists/refs/heads/main/dl/daddyliveevents.m3u" | \
          sed -e 's|https://tinyurl.com/lattedl|https://kerimmkirac-daddyliveevents.hf.space/watch|g' \
              -e 's|https://raw.githubusercontent.com/patr0nq/link/refs/heads/main/tv-logo/vavoo.png|https://raw.githubusercontent.com/kerimmkirac/CanliTvListe/refs/heads/main/subaicon.jpeg|g' \
          > daddyliveevents.m3u



        
      
      
      
          
      - name: DeÄŸiÅŸiklik KontrolÃ¼
        id: degisiklik_kontrol
        run: |
          git diff --quiet . || echo "degisiklik=true" >> $GITHUB_OUTPUT
          
      - name: DeÄŸiÅŸiklikleri Commit Et
        if: steps.degisiklik_kontrol.outputs.degisiklik == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "ğŸ”„ TÃ¼m listeler gÃ¼ncellendi (TRGoals, MonoTV & CanliTV)" -m "ğŸ“º Domain kontrolÃ¼ ve M3U gÃ¼ncellemeleri tamamlandÄ±" -m "ğŸ•’ Otomatik iÅŸlem - $GITHUB_SHA"
          git push
