# Bu araÃ§ @keyiflerolsun tarafÄ±ndan | @KekikAkademi iÃ§in yazÄ±lmÄ±ÅŸtÄ±r.

name: TRGoals, MonoTV ve M3U GÃ¼ncelleme Workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'  # Her 10 dakikada bir Ã§alÄ±ÅŸÄ±r

jobs:
  DomainKontrol:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    permissions:
      contents: write

    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v4.2.2

      - name: Python 3.11.8 YÃ¼kle
        uses: actions/setup-python@v5.3.0
        with:
          python-version: 3.11.8

      - name: Gereksinimleri Kur
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools wheel Kekik httpx parsel

      - name: TRGoals.py Ã‡alÄ±ÅŸtÄ±r
        run: python TRGoals.py

      - name: MonoTV.py Ã‡alÄ±ÅŸtÄ±r
        run: python MonoTV.py
        
      - name: TRGoals2.py Ã‡alÄ±ÅŸtÄ±r
        run: python trgoals2.py

      - name: MonoTV2.py Ã‡alÄ±ÅŸtÄ±r
        run: python monotv2.py

      - name: DeÄŸiÅŸiklik KontrolÃ¼
        id: degisiklik_kontrol
        run: |
          git diff --quiet . || echo "degisiklik=true" >> $GITHUB_OUTPUT

      - name: DeÄŸiÅŸiklikleri Commit Et
        if: steps.degisiklik_kontrol.outputs.degisiklik == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "â™»ï¸ YayÄ±n linkleri gÃ¼ncellendi (TRGoals & MonoTV)" -m "ğŸ•’ Otomatik iÅŸlem - $GITHUB_SHA"
          git push

  update-m3u:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v4

      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Gerekli Paketleri Kur
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: M3U Listesini Ä°ndir ve GÃ¼ncelle
        run: |
          curl -s "https://raw.githubusercontent.com/Sakubaba00/saku/refs/heads/main/playlist1.m3u" > yeni.m3u
          python update_m3u.py
          python kerim.py

      - name: DeÄŸiÅŸiklikleri Commit ve Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add yeni.m3u subatv.m3u Kanallar/kerim.m3u
          git commit -m "ğŸ”„ M3U listeleri otomatik olarak gÃ¼ncellendi" || echo "âš ï¸ DeÄŸiÅŸiklik yok"
          git push https://${{ secrets.PAT }}@github.com/kerimmkirac/CanliTvListe.git
